### ISSUE TITLE
User request: backup file meta data

### ISSUE THREAD

**Issue by pdewouters** [humanmade/backupwordpress#403]
The screen that lists all the backups should contain extra info about the backup, e.g. what version of WordPress it was using, and maybe something configurable such as Theme version. This makes trouble-shooting easier if you need to revert to a previous backup.

**Comment by willmot** [comment]
We can potentially pull this directly from database / files within the backup (see #44).

If that's not reasonable then we'll need to start generating and storing this information at the point the backup is taken.

- [ ] When a backup is taken, capture relevant site meta/status information
- [ ] Store that information somewhere, I think we'd ideally store inside the backup as a json string inside a hidden file (`.backup_meta` or something).
- [ ] Pull the information from that file and display in the list table
